package com.sen.springboot.mapper;

import com.sen.springboot.model.Permission;
import com.sen.springboot.model.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    long countByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int deleteByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Delete({
        "delete from tb_permission",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Insert({
        "insert into tb_permission (id, permission, ",
        "description, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{permission,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    List<Permission> selectByExampleWithRowbounds(PermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    List<Permission> selectByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Select({
        "select",
        "id, permission, description, create_time, update_time",
        "from tb_permission",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.sen.springboot.mapper.PermissionMapper.BaseResultMap")
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Update({
        "update tb_permission",
        "set permission = #{permission,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Permission record);
}