package com.sen.springboot.mapper;

import com.sen.springboot.model.UserMapRole;
import com.sen.springboot.model.UserMapRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface UserMapRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    long countByExample(UserMapRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int deleteByExample(UserMapRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Delete({
        "delete from tb_user_role",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Insert({
        "insert into tb_user_role (id, user_id, ",
        "role_id, create_time, ",
        "update_time)",
        "values (#{id,jdbcType=BIGINT}, #{userId,jdbcType=BIGINT}, ",
        "#{roleId,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserMapRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int insertSelective(UserMapRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    List<UserMapRole> selectByExampleWithRowbounds(UserMapRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    List<UserMapRole> selectByExample(UserMapRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Select({
        "select",
        "id, user_id, role_id, create_time, update_time",
        "from tb_user_role",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.sen.springboot.mapper.UserMapRoleMapper.BaseResultMap")
    UserMapRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserMapRole record, @Param("example") UserMapRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int updateByExample(@Param("record") UserMapRole record, @Param("example") UserMapRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    int updateByPrimaryKeySelective(UserMapRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated Mon Dec 06 21:26:20 CST 2021
     */
    @Update({
        "update tb_user_role",
        "set user_id = #{userId,jdbcType=BIGINT},",
          "role_id = #{roleId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserMapRole record);
}