package com.sen.springboot.model;

import java.io.Serializable;
import java.util.Date;

public class Permission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.id
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.description
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.create_time
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_permission.update_time
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.id
     *
     * @return the value of tb_permission.id
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Permission withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.id
     *
     * @param id the value for tb_permission.id
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.permission
     *
     * @return the value of tb_permission.permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Permission withPermission(String permission) {
        this.setPermission(permission);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.permission
     *
     * @param permission the value for tb_permission.permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.description
     *
     * @return the value of tb_permission.description
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Permission withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.description
     *
     * @param description the value for tb_permission.description
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.create_time
     *
     * @return the value of tb_permission.create_time
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Permission withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.create_time
     *
     * @param createTime the value for tb_permission.create_time
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_permission.update_time
     *
     * @return the value of tb_permission.update_time
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public Permission withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_permission.update_time
     *
     * @param updateTime the value for tb_permission.update_time
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_permission
     *
     * @mbg.generated Fri Dec 17 11:07:15 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", permission=").append(permission);
        sb.append(", description=").append(description);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}