spring:
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
  freemarker:
    cache: false
  datasource:
    product:
      jdbc-url: jdbc:mysql://112.74.82.69:3306/blog?serverTimezone=GMT&characterEncoding=utf8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 112.74.82.69
    port: 6379
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
    timeout: 10000
    password: 123456
  register:
    expire-time: 300
    lock-time: 60 #验证码限制发送间隔
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.sen.springboot.model
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true

debug: true